### ISSUE TITLE
Let Admin create new users for their organization

### ISSUE THREAD

**Issue by jastee07** [jastee07/swe-project#10]
very similar to the organization registration method. 

Check organizations.js line 16.
Restrict route to admin users only.

Maybe factor out salt generator, so we don't have to write the same code twice.

**Comment by mjshalash** [comment]
Do you want the admin to be able to create passwords for their users or what is the dynamic there?

**Comment by mjshalash** [comment]
Do we want the admin to just be able to set the password for the user?
