### ISSUE TITLE
Member List page for an admin to select and edit a user

### ISSUE THREAD

**Issue by mjshalash** [jastee07/swe-project#47]

**Comment by mjshalash** [comment]
This could be grouped with the Add User menu option

**Comment by jastee07** [comment]
We should move the add user button to this page, and have it redirect here instead of the dashboard

**Comment by mjshalash** [comment]
> We should move the add user button to this page, and have it redirect here instead of the dashboard

This is being worked on in the member-list-page branch, not finished yet
